//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ClientUserMap> UsersByClients(global::System.Nullable<int> Client)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.ClientUserMap> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.ClientUserMap>("ClientUserMaps"),
                (c) => (Client.HasValue && (c.Id == Client)));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Ticket))
            {
                return new global::LightSwitchApplication.Implementation.Ticket();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Action))
            {
                return new global::LightSwitchApplication.Implementation.Action();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ClientUserMap))
            {
                return new global::LightSwitchApplication.Implementation.ClientUserMap();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ProjectClientMap))
            {
                return new global::LightSwitchApplication.Implementation.ProjectClientMap();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Ticket))
            {
                return new global::LightSwitchApplication.Implementation.Ticket();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Action))
            {
                return new global::LightSwitchApplication.Implementation.Action();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ClientUserMap))
            {
                return new global::LightSwitchApplication.Implementation.ClientUserMap();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectClientMap))
            {
                return new global::LightSwitchApplication.Implementation.ProjectClientMap();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Ticket) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Ticket);
            }
            if (typeof(global::LightSwitchApplication.Action) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Action);
            }
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.User) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.User);
            }
            if (typeof(global::LightSwitchApplication.ClientUserMap) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ClientUserMap);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.ProjectClientMap) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectClientMap);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Ticket :
        global::LightSwitchApplication.Ticket.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Actions
        {
            get
            {
                return this.Actions;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("User");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Project");
                }
            }
        }
        
        partial void OnTicket_ClientChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnTicket_UserChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("User");
            }
        }
        
        partial void OnTicket_ProjectChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Project");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Action :
        global::LightSwitchApplication.Action.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Action.DetailsClass.IImplementation.Ticket
        {
            get
            {
                return this.Ticket;
            }
            set
            {
                this.Ticket = (global::LightSwitchApplication.Implementation.Ticket)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        partial void OnAction_TicketChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Ticket");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.ClientUserMaps
        {
            get
            {
                return this.ClientUserMaps;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.ProjectClientMaps
        {
            get
            {
                return this.ProjectClientMaps;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class User :
        global::LightSwitchApplication.User.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.ClientUserMaps
        {
            get
            {
                return this.ClientUserMaps;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ClientUserMap :
        global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("User");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        partial void OnClientUserMap_UserChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("User");
            }
        }
        
        partial void OnClientUserMap_ClientChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectClientMaps
        {
            get
            {
                return this.ProjectClientMaps;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectClientMap :
        global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Project");
                }
            }
        }
        
        partial void OnProjectClientMap_ClientChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnProjectClientMap_ProjectChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Project");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

