//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Ticket
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Ticket :
        global::LightSwitchApplication.Ticket.DetailsClass.IImplementation
    {
        partial void OnTicket_ClientChanged()
        {
            this.___OnPropertyChanged("Ticket_Client");
            this.___OnPropertyChanged("Client");
        }
        
        partial void OnTicket_UserChanged()
        {
            this.___OnPropertyChanged("Ticket_User");
            this.___OnPropertyChanged("User");
        }
        
        partial void OnTicket_ProjectChanged()
        {
            this.___OnPropertyChanged("Ticket_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnShortDescriptionChanged()
        {
            this.___OnPropertyChanged("ShortDescription");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnDateOpenedChanged()
        {
            this.___OnPropertyChanged("DateOpened");
        }
        
        partial void OnDateClosedChanged()
        {
            this.___OnPropertyChanged("DateClosed");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Actions
        {
            get
            {
                return this.Actions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Action> __Actions
        {
            get
            {
                if (this.___Actions == null)
                {
                    this.___Actions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Action>(
                        this,
                        "Actions",
                        () => this._Actions,
                        e => global::System.Object.Equals(e.Action_Ticket, this.Id));
                }
                return this.___Actions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Action> ___Actions;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __Client
        {
            get
            {
                if (this.___Client == null)
                {
                    this.___Client = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "Client",
                        new string[] { "Ticket_Client" },
                        e => global::System.Object.Equals(e.Id, this.Ticket_Client),
                        () => this._Client,
                        e => this._Client = e);
                }
                return this.___Client;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___Client;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> __User
        {
            get
            {
                if (this.___User == null)
                {
                    this.___User = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User>(
                        this,
                        "User",
                        new string[] { "Ticket_User" },
                        e => global::System.Object.Equals(e.Id, this.Ticket_User),
                        () => this._User,
                        e => this._User = e);
                }
                return this.___User;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> ___User;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Ticket.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "Ticket_Project" },
                        e => global::System.Object.Equals(e.Id, this.Ticket_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
    }
    #endregion
    
    #region Action
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Action :
        global::LightSwitchApplication.Action.DetailsClass.IImplementation
    {
        partial void OnAction_TicketChanged()
        {
            this.___OnPropertyChanged("Action_Ticket");
            this.___OnPropertyChanged("Ticket");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnActionDateChanged()
        {
            this.___OnPropertyChanged("ActionDate");
        }
        
        partial void OnActionTextChanged()
        {
            this.___OnPropertyChanged("ActionText");
        }
        
        partial void OnTimeChanged()
        {
            this.___OnPropertyChanged("Time");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Action.DetailsClass.IImplementation.Ticket
        {
            get
            {
                return this.Ticket;
            }
            set
            {
                this.Ticket = (global::LightSwitchApplication.Implementation.Ticket)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Ticket> __Ticket
        {
            get
            {
                if (this.___Ticket == null)
                {
                    this.___Ticket = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Ticket>(
                        this,
                        "Ticket",
                        new string[] { "Action_Ticket" },
                        e => global::System.Object.Equals(e.Id, this.Action_Ticket),
                        () => this._Ticket,
                        e => this._Ticket = e);
                }
                return this.___Ticket;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Ticket> ___Ticket;
        
    }
    #endregion
    
    #region Client
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnIsExternalChanged()
        {
            this.___OnPropertyChanged("IsExternal");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.ClientUserMaps
        {
            get
            {
                return this.ClientUserMaps;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap> __ClientUserMaps
        {
            get
            {
                if (this.___ClientUserMaps == null)
                {
                    this.___ClientUserMaps = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap>(
                        this,
                        "ClientUserMaps",
                        () => this._ClientUserMaps,
                        e => global::System.Object.Equals(e.ClientUserMap_Client, this.Id));
                }
                return this.___ClientUserMaps;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap> ___ClientUserMaps;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> __Tickets
        {
            get
            {
                if (this.___Tickets == null)
                {
                    this.___Tickets = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket>(
                        this,
                        "Tickets",
                        () => this._Tickets,
                        e => global::System.Object.Equals(e.Ticket_Client, this.Id));
                }
                return this.___Tickets;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> ___Tickets;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.ProjectClientMaps
        {
            get
            {
                return this.ProjectClientMaps;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap> __ProjectClientMaps
        {
            get
            {
                if (this.___ProjectClientMaps == null)
                {
                    this.___ProjectClientMaps = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap>(
                        this,
                        "ProjectClientMaps",
                        () => this._ProjectClientMaps,
                        e => global::System.Object.Equals(e.ProjectClientMap_Client, this.Id));
                }
                return this.___ProjectClientMaps;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap> ___ProjectClientMaps;
        
    }
    #endregion
    
    #region User
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class User :
        global::LightSwitchApplication.User.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnMiddleNameChanged()
        {
            this.___OnPropertyChanged("MiddleName");
        }
        
        partial void OnADUserNameChanged()
        {
            this.___OnPropertyChanged("ADUserName");
        }
        
        partial void OnADsidChanged()
        {
            this.___OnPropertyChanged("ADsid");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnIsADChanged()
        {
            this.___OnPropertyChanged("IsAD");
        }
        
        partial void OnIsTechChanged()
        {
            this.___OnPropertyChanged("IsTech");
        }
        
        partial void OnIsQueueChanged()
        {
            this.___OnPropertyChanged("IsQueue");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.ClientUserMaps
        {
            get
            {
                return this.ClientUserMaps;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap> __ClientUserMaps
        {
            get
            {
                if (this.___ClientUserMaps == null)
                {
                    this.___ClientUserMaps = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap>(
                        this,
                        "ClientUserMaps",
                        () => this._ClientUserMaps,
                        e => global::System.Object.Equals(e.ClientUserMap_User, this.Id));
                }
                return this.___ClientUserMaps;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ClientUserMap> ___ClientUserMaps;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.User.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> __Tickets
        {
            get
            {
                if (this.___Tickets == null)
                {
                    this.___Tickets = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket>(
                        this,
                        "Tickets",
                        () => this._Tickets,
                        e => global::System.Object.Equals(e.Ticket_User, this.Id));
                }
                return this.___Tickets;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> ___Tickets;
        
    }
    #endregion
    
    #region ClientUserMap
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ClientUserMap :
        global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation
    {
        partial void OnClientUserMap_UserChanged()
        {
            this.___OnPropertyChanged("ClientUserMap_User");
            this.___OnPropertyChanged("User");
        }
        
        partial void OnClientUserMap_ClientChanged()
        {
            this.___OnPropertyChanged("ClientUserMap_Client");
            this.___OnPropertyChanged("Client");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation.User
        {
            get
            {
                return this.User;
            }
            set
            {
                this.User = (global::LightSwitchApplication.Implementation.User)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> __User
        {
            get
            {
                if (this.___User == null)
                {
                    this.___User = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User>(
                        this,
                        "User",
                        new string[] { "ClientUserMap_User" },
                        e => global::System.Object.Equals(e.Id, this.ClientUserMap_User),
                        () => this._User,
                        e => this._User = e);
                }
                return this.___User;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.User> ___User;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientUserMap.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __Client
        {
            get
            {
                if (this.___Client == null)
                {
                    this.___Client = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "Client",
                        new string[] { "ClientUserMap_Client" },
                        e => global::System.Object.Equals(e.Id, this.ClientUserMap_Client),
                        () => this._Client,
                        e => this._Client = e);
                }
                return this.___Client;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___Client;
        
    }
    #endregion
    
    #region Project
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.ProjectClientMaps
        {
            get
            {
                return this.ProjectClientMaps;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap> __ProjectClientMaps
        {
            get
            {
                if (this.___ProjectClientMaps == null)
                {
                    this.___ProjectClientMaps = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap>(
                        this,
                        "ProjectClientMaps",
                        () => this._ProjectClientMaps,
                        e => global::System.Object.Equals(e.ProjectClientMap_Project, this.Id));
                }
                return this.___ProjectClientMaps;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ProjectClientMap> ___ProjectClientMaps;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.Tickets
        {
            get
            {
                return this.Tickets;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> __Tickets
        {
            get
            {
                if (this.___Tickets == null)
                {
                    this.___Tickets = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket>(
                        this,
                        "Tickets",
                        () => this._Tickets,
                        e => global::System.Object.Equals(e.Ticket_Project, this.Id));
                }
                return this.___Tickets;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Ticket> ___Tickets;
        
    }
    #endregion
    
    #region ProjectClientMap
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ProjectClientMap :
        global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation
    {
        partial void OnProjectClientMap_ClientChanged()
        {
            this.___OnPropertyChanged("ProjectClientMap_Client");
            this.___OnPropertyChanged("Client");
        }
        
        partial void OnProjectClientMap_ProjectChanged()
        {
            this.___OnPropertyChanged("ProjectClientMap_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> __Client
        {
            get
            {
                if (this.___Client == null)
                {
                    this.___Client = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client>(
                        this,
                        "Client",
                        new string[] { "ProjectClientMap_Client" },
                        e => global::System.Object.Equals(e.Id, this.ProjectClientMap_Client),
                        () => this._Client,
                        e => this._Client = e);
                }
                return this.___Client;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Client> ___Client;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ProjectClientMap.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "ProjectClientMap_Project" },
                        e => global::System.Object.Equals(e.Id, this.ProjectClientMap_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Ticket))
            {
                return new global::LightSwitchApplication.Implementation.Ticket();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Action))
            {
                return new global::LightSwitchApplication.Implementation.Action();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.User))
            {
                return new global::LightSwitchApplication.Implementation.User();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ClientUserMap))
            {
                return new global::LightSwitchApplication.Implementation.ClientUserMap();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ProjectClientMap))
            {
                return new global::LightSwitchApplication.Implementation.ProjectClientMap();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Ticket) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Ticket);
            }
            if (typeof(global::LightSwitchApplication.Action) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Action);
            }
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.User) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.User);
            }
            if (typeof(global::LightSwitchApplication.ClientUserMap) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ClientUserMap);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.ProjectClientMap) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ProjectClientMap);
            }
            return null;
        }
    }
}
