//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/17/2013 10:56:16 AM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationDataObjectContext in the schema.
    /// </summary>
    public partial class ApplicationDataObjectContext : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationDataObjectContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("LightSwitchApplication", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("LightSwitchApplication.Implementation", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Ticket> Tickets
        {
            get
            {
                if ((this._Tickets == null))
                {
                    this._Tickets = base.CreateQuery<Ticket>("Tickets");
                }
                return this._Tickets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Ticket> _Tickets;
        /// <summary>
        /// There are no comments for Actions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Action> Actions
        {
            get
            {
                if ((this._Actions == null))
                {
                    this._Actions = base.CreateQuery<Action>("Actions");
                }
                return this._Actions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Action> _Actions;
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Client> Clients
        {
            get
            {
                if ((this._Clients == null))
                {
                    this._Clients = base.CreateQuery<Client>("Clients");
                }
                return this._Clients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Client> _Clients;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for ClientUserMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ClientUserMap> ClientUserMaps
        {
            get
            {
                if ((this._ClientUserMaps == null))
                {
                    this._ClientUserMaps = base.CreateQuery<ClientUserMap>("ClientUserMaps");
                }
                return this._ClientUserMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ClientUserMap> _ClientUserMaps;
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Project> Projects
        {
            get
            {
                if ((this._Projects == null))
                {
                    this._Projects = base.CreateQuery<Project>("Projects");
                }
                return this._Projects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Project> _Projects;
        /// <summary>
        /// There are no comments for ProjectClientMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProjectClientMap> ProjectClientMaps
        {
            get
            {
                if ((this._ProjectClientMaps == null))
                {
                    this._ProjectClientMaps = base.CreateQuery<ProjectClientMap>("ProjectClientMaps");
                }
                return this._ProjectClientMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProjectClientMap> _ProjectClientMaps;
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTickets(Ticket ticket)
        {
            base.AddObject("Tickets", ticket);
        }
        /// <summary>
        /// There are no comments for Actions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActions(Action action)
        {
            base.AddObject("Actions", action);
        }
        /// <summary>
        /// There are no comments for Clients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        /// <summary>
        /// There are no comments for ClientUserMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClientUserMaps(ClientUserMap clientUserMap)
        {
            base.AddObject("ClientUserMaps", clientUserMap);
        }
        /// <summary>
        /// There are no comments for Projects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
        /// <summary>
        /// There are no comments for ProjectClientMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProjectClientMaps(ProjectClientMap projectClientMap)
        {
            base.AddObject("ProjectClientMaps", projectClientMap);
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Ticket in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tickets")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Ticket : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Ticket object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="shortDescription">Initial value of ShortDescription.</param>
        /// <param name="dateOpened">Initial value of DateOpened.</param>
        /// <param name="ticket_Client">Initial value of Ticket_Client.</param>
        /// <param name="ticket_User">Initial value of Ticket_User.</param>
        /// <param name="ticket_Project">Initial value of Ticket_Project.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Ticket CreateTicket(int ID, byte[] rowVersion, string shortDescription, global::System.DateTime dateOpened, int ticket_Client, int ticket_User, int ticket_Project)
        {
            Ticket ticket = new Ticket();
            ticket.Id = ID;
            ticket.RowVersion = rowVersion;
            ticket.ShortDescription = shortDescription;
            ticket.DateOpened = dateOpened;
            ticket.Ticket_Client = ticket_Client;
            ticket.Ticket_User = ticket_User;
            ticket.Ticket_Project = ticket_Project;
            return ticket;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property ShortDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortDescription
        {
            get
            {
                return this._ShortDescription;
            }
            set
            {
                this.OnShortDescriptionChanging(value);
                if (object.Equals(this.ShortDescription, value))
                {
                    return;
                }
                this._ShortDescription = value;
                this.OnShortDescriptionChanged();
                this.OnPropertyChanged("ShortDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortDescription;
        partial void OnShortDescriptionChanging(string value);
        partial void OnShortDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                if (object.Equals(this.Description, value))
                {
                    return;
                }
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DateOpened in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateOpened
        {
            get
            {
                return this._DateOpened;
            }
            set
            {
                this.OnDateOpenedChanging(value);
                if (object.Equals(this.DateOpened, value))
                {
                    return;
                }
                this._DateOpened = value;
                this.OnDateOpenedChanged();
                this.OnPropertyChanged("DateOpened");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateOpened;
        partial void OnDateOpenedChanging(global::System.DateTime value);
        partial void OnDateOpenedChanged();
        /// <summary>
        /// There are no comments for Property DateClosed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateClosed
        {
            get
            {
                return this._DateClosed;
            }
            set
            {
                this.OnDateClosedChanging(value);
                if (object.Equals(this.DateClosed, value))
                {
                    return;
                }
                this._DateClosed = value;
                this.OnDateClosedChanged();
                this.OnPropertyChanged("DateClosed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateClosed;
        partial void OnDateClosedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateClosedChanged();
        /// <summary>
        /// There are no comments for Property Ticket_Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Ticket_Client
        {
            get
            {
                return this._Ticket_Client;
            }
            set
            {
                this.OnTicket_ClientChanging(value);
                if (object.Equals(this.Ticket_Client, value))
                {
                    return;
                }
                this._Ticket_Client = value;
                this.OnTicket_ClientChanged();
                this.OnPropertyChanged("Ticket_Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Ticket_Client;
        partial void OnTicket_ClientChanging(int value);
        partial void OnTicket_ClientChanged();
        /// <summary>
        /// There are no comments for Property Ticket_User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Ticket_User
        {
            get
            {
                return this._Ticket_User;
            }
            set
            {
                this.OnTicket_UserChanging(value);
                if (object.Equals(this.Ticket_User, value))
                {
                    return;
                }
                this._Ticket_User = value;
                this.OnTicket_UserChanged();
                this.OnPropertyChanged("Ticket_User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Ticket_User;
        partial void OnTicket_UserChanging(int value);
        partial void OnTicket_UserChanged();
        /// <summary>
        /// There are no comments for Property Ticket_Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Ticket_Project
        {
            get
            {
                return this._Ticket_Project;
            }
            set
            {
                this.OnTicket_ProjectChanging(value);
                if (object.Equals(this.Ticket_Project, value))
                {
                    return;
                }
                this._Ticket_Project = value;
                this.OnTicket_ProjectChanged();
                this.OnPropertyChanged("Ticket_Project");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Ticket_Project;
        partial void OnTicket_ProjectChanging(int value);
        partial void OnTicket_ProjectChanged();
        /// <summary>
        /// There are no comments for Actions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Action> Actions
        {
            get
            {
                this.@__Actions.EnsureValueInitialized();
                return this._Actions;
            }
            set
            {
                this._Actions = value;
                this.OnPropertyChanged("Actions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Action> _Actions = new global::System.Data.Services.Client.DataServiceCollection<Action>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Client Client
        {
            get
            {
                this.@__Client.EnsureValueInitialized();
                return this._Client;
            }
            set
            {
                Client previous = this.Client;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Client = null;
                    this.@__Client.OnValueSet();
                    previous.Tickets.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Ticket_Client = value.Id;
                    }
                    else
                    {
                        this.Ticket_Client = default(int);
                    }
                }
                this._Client = value;
                this.@__Client.OnValueSet();
                if ((value != null))
                {
                    value.@__Tickets.Add(this);
                }
                this.___OnPropertyChanged("Client");
                this.OnPropertyChanged("Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Client _Client;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                this.@__User.EnsureValueInitialized();
                return this._User;
            }
            set
            {
                User previous = this.User;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._User = null;
                    this.@__User.OnValueSet();
                    previous.Tickets.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Ticket_User = value.Id;
                    }
                    else
                    {
                        this.Ticket_User = default(int);
                    }
                }
                this._User = value;
                this.@__User.OnValueSet();
                if ((value != null))
                {
                    value.@__Tickets.Add(this);
                }
                this.___OnPropertyChanged("User");
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project
        {
            get
            {
                this.@__Project.EnsureValueInitialized();
                return this._Project;
            }
            set
            {
                Project previous = this.Project;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Project = null;
                    this.@__Project.OnValueSet();
                    previous.Tickets.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Ticket_Project = value.Id;
                    }
                    else
                    {
                        this.Ticket_Project = default(int);
                    }
                }
                this._Project = value;
                this.@__Project.OnValueSet();
                if ((value != null))
                {
                    value.@__Tickets.Add(this);
                }
                this.___OnPropertyChanged("Project");
                this.OnPropertyChanged("Project");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Action in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Actions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Action : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Action object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="actionDate">Initial value of ActionDate.</param>
        /// <param name="actionText">Initial value of ActionText.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="action_Ticket">Initial value of Action_Ticket.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Action CreateAction(int ID, byte[] rowVersion, global::System.DateTime actionDate, string actionText, decimal time, int action_Ticket)
        {
            Action action = new Action();
            action.Id = ID;
            action.RowVersion = rowVersion;
            action.ActionDate = actionDate;
            action.ActionText = actionText;
            action.Time = time;
            action.Action_Ticket = action_Ticket;
            return action;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property ActionDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ActionDate
        {
            get
            {
                return this._ActionDate;
            }
            set
            {
                this.OnActionDateChanging(value);
                if (object.Equals(this.ActionDate, value))
                {
                    return;
                }
                this._ActionDate = value;
                this.OnActionDateChanged();
                this.OnPropertyChanged("ActionDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ActionDate;
        partial void OnActionDateChanging(global::System.DateTime value);
        partial void OnActionDateChanged();
        /// <summary>
        /// There are no comments for Property ActionText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionText
        {
            get
            {
                return this._ActionText;
            }
            set
            {
                this.OnActionTextChanging(value);
                if (object.Equals(this.ActionText, value))
                {
                    return;
                }
                this._ActionText = value;
                this.OnActionTextChanged();
                this.OnPropertyChanged("ActionText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionText;
        partial void OnActionTextChanging(string value);
        partial void OnActionTextChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                if (object.Equals(this.Time, value))
                {
                    return;
                }
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Time;
        partial void OnTimeChanging(decimal value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property Action_Ticket in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Action_Ticket
        {
            get
            {
                return this._Action_Ticket;
            }
            set
            {
                this.OnAction_TicketChanging(value);
                if (object.Equals(this.Action_Ticket, value))
                {
                    return;
                }
                this._Action_Ticket = value;
                this.OnAction_TicketChanged();
                this.OnPropertyChanged("Action_Ticket");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Action_Ticket;
        partial void OnAction_TicketChanging(int value);
        partial void OnAction_TicketChanged();
        /// <summary>
        /// There are no comments for Ticket in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Ticket Ticket
        {
            get
            {
                this.@__Ticket.EnsureValueInitialized();
                return this._Ticket;
            }
            set
            {
                Ticket previous = this.Ticket;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Ticket = null;
                    this.@__Ticket.OnValueSet();
                    previous.Actions.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Action_Ticket = value.Id;
                    }
                    else
                    {
                        this.Action_Ticket = default(int);
                    }
                }
                this._Ticket = value;
                this.@__Ticket.OnValueSet();
                if ((value != null))
                {
                    value.@__Actions.Add(this);
                }
                this.___OnPropertyChanged("Ticket");
                this.OnPropertyChanged("Ticket");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Ticket _Ticket;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Client in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Clients")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Client : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Client CreateClient(int ID, byte[] rowVersion, string name)
        {
            Client client = new Client();
            client.Id = ID;
            client.RowVersion = rowVersion;
            client.Name = name;
            return client;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property IsExternal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsExternal
        {
            get
            {
                return this._IsExternal;
            }
            set
            {
                this.OnIsExternalChanging(value);
                if (object.Equals(this.IsExternal, value))
                {
                    return;
                }
                this._IsExternal = value;
                this.OnIsExternalChanged();
                this.OnPropertyChanged("IsExternal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsExternal;
        partial void OnIsExternalChanging(global::System.Nullable<bool> value);
        partial void OnIsExternalChanged();
        /// <summary>
        /// There are no comments for ClientUserMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ClientUserMap> ClientUserMaps
        {
            get
            {
                this.@__ClientUserMaps.EnsureValueInitialized();
                return this._ClientUserMaps;
            }
            set
            {
                this._ClientUserMaps = value;
                this.OnPropertyChanged("ClientUserMaps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ClientUserMap> _ClientUserMaps = new global::System.Data.Services.Client.DataServiceCollection<ClientUserMap>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Ticket> Tickets
        {
            get
            {
                this.@__Tickets.EnsureValueInitialized();
                return this._Tickets;
            }
            set
            {
                this._Tickets = value;
                this.OnPropertyChanged("Tickets");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Ticket> _Tickets = new global::System.Data.Services.Client.DataServiceCollection<Ticket>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ProjectClientMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap> ProjectClientMaps
        {
            get
            {
                this.@__ProjectClientMaps.EnsureValueInitialized();
                return this._ProjectClientMaps;
            }
            set
            {
                this._ProjectClientMaps = value;
                this.OnPropertyChanged("ProjectClientMaps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap> _ProjectClientMaps = new global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class User : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(int ID, byte[] rowVersion, string firstName)
        {
            User user = new User();
            user.Id = ID;
            user.RowVersion = rowVersion;
            user.FirstName = firstName;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                if (object.Equals(this.FirstName, value))
                {
                    return;
                }
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                if (object.Equals(this.LastName, value))
                {
                    return;
                }
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property MiddleName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this.OnMiddleNameChanging(value);
                if (object.Equals(this.MiddleName, value))
                {
                    return;
                }
                this._MiddleName = value;
                this.OnMiddleNameChanged();
                this.OnPropertyChanged("MiddleName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MiddleName;
        partial void OnMiddleNameChanging(string value);
        partial void OnMiddleNameChanged();
        /// <summary>
        /// There are no comments for Property ADUserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADUserName
        {
            get
            {
                return this._ADUserName;
            }
            set
            {
                this.OnADUserNameChanging(value);
                if (object.Equals(this.ADUserName, value))
                {
                    return;
                }
                this._ADUserName = value;
                this.OnADUserNameChanged();
                this.OnPropertyChanged("ADUserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADUserName;
        partial void OnADUserNameChanging(string value);
        partial void OnADUserNameChanged();
        /// <summary>
        /// There are no comments for Property ADsid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ADsid
        {
            get
            {
                return this._ADsid;
            }
            set
            {
                this.OnADsidChanging(value);
                if (object.Equals(this.ADsid, value))
                {
                    return;
                }
                this._ADsid = value;
                this.OnADsidChanged();
                this.OnPropertyChanged("ADsid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ADsid;
        partial void OnADsidChanging(string value);
        partial void OnADsidChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                if (object.Equals(this.Email, value))
                {
                    return;
                }
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property IsAD in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsAD
        {
            get
            {
                return this._IsAD;
            }
            set
            {
                this.OnIsADChanging(value);
                if (object.Equals(this.IsAD, value))
                {
                    return;
                }
                this._IsAD = value;
                this.OnIsADChanged();
                this.OnPropertyChanged("IsAD");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsAD;
        partial void OnIsADChanging(global::System.Nullable<bool> value);
        partial void OnIsADChanged();
        /// <summary>
        /// There are no comments for Property IsTech in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsTech
        {
            get
            {
                return this._IsTech;
            }
            set
            {
                this.OnIsTechChanging(value);
                if (object.Equals(this.IsTech, value))
                {
                    return;
                }
                this._IsTech = value;
                this.OnIsTechChanged();
                this.OnPropertyChanged("IsTech");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsTech;
        partial void OnIsTechChanging(global::System.Nullable<bool> value);
        partial void OnIsTechChanged();
        /// <summary>
        /// There are no comments for Property IsQueue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsQueue
        {
            get
            {
                return this._IsQueue;
            }
            set
            {
                this.OnIsQueueChanging(value);
                if (object.Equals(this.IsQueue, value))
                {
                    return;
                }
                this._IsQueue = value;
                this.OnIsQueueChanged();
                this.OnPropertyChanged("IsQueue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsQueue;
        partial void OnIsQueueChanging(global::System.Nullable<bool> value);
        partial void OnIsQueueChanged();
        /// <summary>
        /// There are no comments for ClientUserMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ClientUserMap> ClientUserMaps
        {
            get
            {
                this.@__ClientUserMaps.EnsureValueInitialized();
                return this._ClientUserMaps;
            }
            set
            {
                this._ClientUserMaps = value;
                this.OnPropertyChanged("ClientUserMaps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ClientUserMap> _ClientUserMaps = new global::System.Data.Services.Client.DataServiceCollection<ClientUserMap>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Ticket> Tickets
        {
            get
            {
                this.@__Tickets.EnsureValueInitialized();
                return this._Tickets;
            }
            set
            {
                this._Tickets = value;
                this.OnPropertyChanged("Tickets");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Ticket> _Tickets = new global::System.Data.Services.Client.DataServiceCollection<Ticket>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.ClientUserMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ClientUserMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ClientUserMap : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ClientUserMap object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="clientUserMap_User">Initial value of ClientUserMap_User.</param>
        /// <param name="clientUserMap_Client">Initial value of ClientUserMap_Client.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ClientUserMap CreateClientUserMap(int ID, byte[] rowVersion, int clientUserMap_User, int clientUserMap_Client)
        {
            ClientUserMap clientUserMap = new ClientUserMap();
            clientUserMap.Id = ID;
            clientUserMap.RowVersion = rowVersion;
            clientUserMap.ClientUserMap_User = clientUserMap_User;
            clientUserMap.ClientUserMap_Client = clientUserMap_Client;
            return clientUserMap;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property ClientUserMap_User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientUserMap_User
        {
            get
            {
                return this._ClientUserMap_User;
            }
            set
            {
                this.OnClientUserMap_UserChanging(value);
                if (object.Equals(this.ClientUserMap_User, value))
                {
                    return;
                }
                this._ClientUserMap_User = value;
                this.OnClientUserMap_UserChanged();
                this.OnPropertyChanged("ClientUserMap_User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientUserMap_User;
        partial void OnClientUserMap_UserChanging(int value);
        partial void OnClientUserMap_UserChanged();
        /// <summary>
        /// There are no comments for Property ClientUserMap_Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientUserMap_Client
        {
            get
            {
                return this._ClientUserMap_Client;
            }
            set
            {
                this.OnClientUserMap_ClientChanging(value);
                if (object.Equals(this.ClientUserMap_Client, value))
                {
                    return;
                }
                this._ClientUserMap_Client = value;
                this.OnClientUserMap_ClientChanged();
                this.OnPropertyChanged("ClientUserMap_Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientUserMap_Client;
        partial void OnClientUserMap_ClientChanging(int value);
        partial void OnClientUserMap_ClientChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                this.@__User.EnsureValueInitialized();
                return this._User;
            }
            set
            {
                User previous = this.User;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._User = null;
                    this.@__User.OnValueSet();
                    previous.ClientUserMaps.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ClientUserMap_User = value.Id;
                    }
                    else
                    {
                        this.ClientUserMap_User = default(int);
                    }
                }
                this._User = value;
                this.@__User.OnValueSet();
                if ((value != null))
                {
                    value.@__ClientUserMaps.Add(this);
                }
                this.___OnPropertyChanged("User");
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Client Client
        {
            get
            {
                this.@__Client.EnsureValueInitialized();
                return this._Client;
            }
            set
            {
                Client previous = this.Client;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Client = null;
                    this.@__Client.OnValueSet();
                    previous.ClientUserMaps.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ClientUserMap_Client = value.Id;
                    }
                    else
                    {
                        this.ClientUserMap_Client = default(int);
                    }
                }
                this._Client = value;
                this.@__Client.OnValueSet();
                if ((value != null))
                {
                    value.@__ClientUserMaps.Add(this);
                }
                this.___OnPropertyChanged("Client");
                this.OnPropertyChanged("Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Client _Client;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Project in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Projects")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Project : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Project CreateProject(int ID, byte[] rowVersion, string name)
        {
            Project project = new Project();
            project.Id = ID;
            project.RowVersion = rowVersion;
            project.Name = name;
            return project;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for ProjectClientMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap> ProjectClientMaps
        {
            get
            {
                this.@__ProjectClientMaps.EnsureValueInitialized();
                return this._ProjectClientMaps;
            }
            set
            {
                this._ProjectClientMaps = value;
                this.OnPropertyChanged("ProjectClientMaps");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap> _ProjectClientMaps = new global::System.Data.Services.Client.DataServiceCollection<ProjectClientMap>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tickets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Ticket> Tickets
        {
            get
            {
                this.@__Tickets.EnsureValueInitialized();
                return this._Tickets;
            }
            set
            {
                this._Tickets = value;
                this.OnPropertyChanged("Tickets");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Ticket> _Tickets = new global::System.Data.Services.Client.DataServiceCollection<Ticket>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.ProjectClientMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProjectClientMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ProjectClientMap : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProjectClientMap object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        /// <param name="projectClientMap_Client">Initial value of ProjectClientMap_Client.</param>
        /// <param name="projectClientMap_Project">Initial value of ProjectClientMap_Project.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ProjectClientMap CreateProjectClientMap(int ID, byte[] rowVersion, int projectClientMap_Client, int projectClientMap_Project)
        {
            ProjectClientMap projectClientMap = new ProjectClientMap();
            projectClientMap.Id = ID;
            projectClientMap.RowVersion = rowVersion;
            projectClientMap.ProjectClientMap_Client = projectClientMap_Client;
            projectClientMap.ProjectClientMap_Project = projectClientMap_Project;
            return projectClientMap;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Property ProjectClientMap_Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectClientMap_Client
        {
            get
            {
                return this._ProjectClientMap_Client;
            }
            set
            {
                this.OnProjectClientMap_ClientChanging(value);
                if (object.Equals(this.ProjectClientMap_Client, value))
                {
                    return;
                }
                this._ProjectClientMap_Client = value;
                this.OnProjectClientMap_ClientChanged();
                this.OnPropertyChanged("ProjectClientMap_Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectClientMap_Client;
        partial void OnProjectClientMap_ClientChanging(int value);
        partial void OnProjectClientMap_ClientChanged();
        /// <summary>
        /// There are no comments for Property ProjectClientMap_Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProjectClientMap_Project
        {
            get
            {
                return this._ProjectClientMap_Project;
            }
            set
            {
                this.OnProjectClientMap_ProjectChanging(value);
                if (object.Equals(this.ProjectClientMap_Project, value))
                {
                    return;
                }
                this._ProjectClientMap_Project = value;
                this.OnProjectClientMap_ProjectChanged();
                this.OnPropertyChanged("ProjectClientMap_Project");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProjectClientMap_Project;
        partial void OnProjectClientMap_ProjectChanging(int value);
        partial void OnProjectClientMap_ProjectChanged();
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Client Client
        {
            get
            {
                this.@__Client.EnsureValueInitialized();
                return this._Client;
            }
            set
            {
                Client previous = this.Client;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Client = null;
                    this.@__Client.OnValueSet();
                    previous.ProjectClientMaps.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ProjectClientMap_Client = value.Id;
                    }
                    else
                    {
                        this.ProjectClientMap_Client = default(int);
                    }
                }
                this._Client = value;
                this.@__Client.OnValueSet();
                if ((value != null))
                {
                    value.@__ProjectClientMaps.Add(this);
                }
                this.___OnPropertyChanged("Client");
                this.OnPropertyChanged("Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Client _Client;
        /// <summary>
        /// There are no comments for Project in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Project Project
        {
            get
            {
                this.@__Project.EnsureValueInitialized();
                return this._Project;
            }
            set
            {
                Project previous = this.Project;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Project = null;
                    this.@__Project.OnValueSet();
                    previous.ProjectClientMaps.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.ProjectClientMap_Project = value.Id;
                    }
                    else
                    {
                        this.ProjectClientMap_Project = default(int);
                    }
                }
                this._Project = value;
                this.@__Project.OnValueSet();
                if ((value != null))
                {
                    value.@__ProjectClientMaps.Add(this);
                }
                this.___OnPropertyChanged("Project");
                this.OnPropertyChanged("Project");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Project _Project;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
