

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class Action : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Action entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Action()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Action(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Action> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Action.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Action_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Action_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ActionDate
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionDate);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ActionText
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionText);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionText, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionText_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionText_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActionText_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Time
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Time);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Time, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Time_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Ticket Ticket
        {
            get
            {
                return global::LightSwitchApplication.Action.DetailsClass.GetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket);
            }
            set
            {
                global::LightSwitchApplication.Action.DetailsClass.SetValue(this, global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticket_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticket_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Ticket_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Action,
                global::LightSwitchApplication.Action.DetailsClass,
                global::LightSwitchApplication.Action.DetailsClass.IImplementation,
                global::LightSwitchApplication.Action.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>.Entry
                __ActionEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>.Entry(
                    global::LightSwitchApplication.Action.DetailsClass.__Action_CreateNew,
                    global::LightSwitchApplication.Action.DetailsClass.__Action_Created,
                    global::LightSwitchApplication.Action.DetailsClass.__Action_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Action __Action_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Action> es)
            {
                return new global::LightSwitchApplication.Action(es);
            }
            private static void __Action_Created(global::LightSwitchApplication.Action e)
            {
                e.Action_Created();
            }
            private static bool __Action_AllowSaveWithErrors(global::LightSwitchApplication.Action e)
            {
                bool result = false;
                e.Action_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Action.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime> ActionDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string> ActionText
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.ActionText) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal> Time
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Time) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket> Ticket
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.DateTime ActionDate { get; set; }
                new string ActionText { get; set; }
                new decimal Time { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Ticket { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime>.Entry
                    ActionDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime>.Entry(
                        "ActionDate",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionDate_OnValueChanged);
                private static void _ActionDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionDate, sf);
                }
                private static bool _ActionDate_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.ActionDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionDate_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionDate_Validate(r);
                }
                private static global::System.DateTime _ActionDate_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionDate;
                }
                private static void _ActionDate_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.ActionDate = global::LightSwitchApplication.Action.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ActionDate_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.ActionDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string>.Entry
                    ActionText = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string>.Entry(
                        "ActionText",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._ActionText_OnValueChanged);
                private static void _ActionText_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._ActionText, sf);
                }
                private static bool _ActionText_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.ActionText_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActionText_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActionText_Validate(r);
                }
                private static string _ActionText_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.ActionText;
                }
                private static void _ActionText_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ActionText = v;
                }
                private static void _ActionText_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.ActionText_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal>.Entry
                    Time = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal>.Entry(
                        "Time",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Time_OnValueChanged);
                private static void _Time_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._Time, sf);
                }
                private static bool _Time_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.Time_IsReadOnly(ref result);
                    return result;
                }
                private static void _Time_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Time_Validate(r);
                }
                private static decimal _Time_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.Time;
                }
                private static void _Time_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Time = v;
                }
                private static void _Time_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.Time_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket>.Entry
                    Ticket = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket>.Entry(
                        "Ticket",
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_Stub,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_ComputeIsReadOnly,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_Validate,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_GetCoreImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_GetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_SetImplementationValue,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_Refresh,
                        global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties._Ticket_OnValueChanged);
                private static void _Ticket_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Action.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket>.Data> c, global::LightSwitchApplication.Action.DetailsClass d, object sf)
                {
                    c(d, ref d._Ticket, sf);
                }
                private static bool _Ticket_ComputeIsReadOnly(global::LightSwitchApplication.Action e)
                {
                    bool result = false;
                    e.Ticket_IsReadOnly(ref result);
                    return result;
                }
                private static void _Ticket_Validate(global::LightSwitchApplication.Action e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Ticket_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Ticket_GetCoreImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.ImplementationEntity.Ticket;
                }
                private static global::LightSwitchApplication.Ticket _Ticket_GetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Ticket, global::LightSwitchApplication.Ticket.DetailsClass>(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket, ref d._Ticket);
                }
                private static void _Ticket_SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass d, global::LightSwitchApplication.Ticket v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket, ref d._Ticket, (i, ev) => i.Ticket = ev, v);
                }
                private static void _Ticket_Refresh(global::LightSwitchApplication.Action.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Action.DetailsClass.PropertySetProperties.Ticket, ref d._Ticket);
                }
                private static void _Ticket_OnValueChanged(global::LightSwitchApplication.Action e)
                {
                    e.Ticket_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::System.DateTime>.Data _ActionDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, string>.Data _ActionText;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, decimal>.Data _Time;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Action, global::LightSwitchApplication.Action.DetailsClass, global::LightSwitchApplication.Ticket>.Data _Ticket;
            
        }
    
        #endregion
    }
    
    #endregion
}
